import "./globals.css";
import Header from "@/comp/header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div style={{ display: "flex", gap: "1rem" }}>
          <Header />
          <div className="pageContainer">{children}</div>
        </div>
      </body>
    </html>
  );
}
